// 昌建誉峰
export const cjyf: Object = {
  total: 39,
  page: 1,
  pagesize: 10,
  resblockCard: {
    communityId: 8872131246462895,
    communityName: "昌建誉峰",
    communityDesc: "塔楼 板楼 塔板结合 | 共11栋 1090户 | 2016-2020年",
    avgUnitPrice: 6847,
    avgUnitPriceDesc: "0.68万元/㎡",
    count: 39,
    countDesc: '在售<i class="_color">39</i>套房源',
    actionUrl: "https://zmd.ke.com/xiaoqu/8872131246462895/",
  },
  list: [
    {
      title: "此房南北通厅通透，客卧朝阳，前后带阳台。",
      desc: "3室2厅/107.32㎡/东/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Bs0Ftrt2y.jpg.210x164.jpg?from=ke.com",
      priceStr: "66万",
      unitPriceStr: "6150元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109426854.html",
      cardType: "二手房",
    },
    {
      title: "北区优质小区 环境好 物业有保证  价格美丽",
      desc: "2室2厅/97.62㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_0Jc5EGTCc_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "59万",
      unitPriceStr: "6044元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106833504.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰双气一楼带院带负一楼3房2厅1卫通厅通透",
      desc: "3室2厅/119.08㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_KTMAYKIAd_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "92.8万",
      unitPriceStr: "7794元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108234191.html",
      cardType: "二手房",
    },
    {
      title: "毛坯，老证，采光充足，环境优美，天中广场，爱家商场",
      desc: "3室2厅/132.16㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_rTB72jy4y_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "85万",
      unitPriceStr: "6432元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110442943.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰三房精装修老证拎包入住双气",
      desc: "3室2厅/98.15㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_jU6fdm79Z_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "70万",
      unitPriceStr: "7132元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107648587.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰南北通透，两梯两户，双气采光好，有证可按揭",
      desc: "4室2厅/142.33㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_pvZ6wJsKq_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "86万",
      unitPriceStr: "6043元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106760489.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰 三房精装老证 拎包入住 看房方便",
      desc: "3室2厅/98.54㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_IM8vbw9eE_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "70万",
      unitPriceStr: "7104元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110375331.html",
      cardType: "二手房",
    },
    {
      title: "纬二路昌建誉峰精装两室两厅带家具家电老票新证",
      desc: "2室2厅/83.96㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_ZMXb3jQhW_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "62万",
      unitPriceStr: "7385元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110762579.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰 2室2厅 南",
      desc: "2室2厅/97.95㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_I4UmByot8_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "70万",
      unitPriceStr: "7147元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111250981.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰位于慎阳路与万和路交叉口",
      desc: "2室2厅/87.35㎡/南/昌建誉峰",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/aa28362d08d307de18e1c4ef3fe0030e-099.jpg.210x164.jpg?from=ke.com",
      priceStr: "62万",
      unitPriceStr: "7098元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110842509.html",
      cardType: "二手房",
    },

    {
      title: "毛坯，老证，采光充足，环境优美，天中广场，爱家商场",
      desc: "3室2厅/132.16㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_rTB72jy4y_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "85万",
      unitPriceStr: "6432元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110442943.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰三房精装修老证拎包入住双气",
      desc: "3室2厅/98.15㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_jU6fdm79Z_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "70万",
      unitPriceStr: "7132元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107648587.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰，乐山路与纬二路交叉口，品质小区",
      desc: "3室2厅/109.09㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_g9UgjOHQB_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "89万",
      unitPriceStr: "8159元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110762571.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰，精装Z央空调，带家具家电。",
      desc: "4室2厅/122.65㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_mJQpsFN3Z.jpg.210x164.jpg?from=ke.com",
      priceStr: "88万",
      unitPriceStr: "7175元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109926193.html",
      cardType: "二手房",
    },
    {
      title: "精装修，户型方正，采光充足，配套成熟",
      desc: "3室2厅/98.15㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "房主自荐",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_izeorQtZr_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "63万",
      unitPriceStr: "6419元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111362447.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰  户型方正 市政府旁 交通便利",
      desc: "2室2厅/98㎡/东/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_xxdjHcNUg_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "66万",
      unitPriceStr: "6735元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110409979.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰 精装三房 双气有地暖 采光充足",
      desc: "3室2厅/115.91㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_z3IiLKirw_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "80万",
      unitPriceStr: "6902元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110946915.html",
      cardType: "二手房",
    },
    {
      title: "户型方正；布局合理；南北通透；采光好。",
      desc: "3室2厅/125.32㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_HswgN6mQ4_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "69万",
      unitPriceStr: "5506元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106946342.html",
      cardType: "二手房",
    },
    {
      title: "纬二路昌建誉峰毛坯三房加10个平方，带8平储藏室",
      desc: "3室1厅/115.91㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_wo9cTdGcz_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "69.6万",
      unitPriceStr: "6005元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110940809.html",
      cardType: "二手房",
    },
    {
      title: "位置好交通便利、配套成熟、户型好。",
      desc: "3室1厅/85.2㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_OvnemMi5C.jpg.210x164.jpg?from=ke.com",
      priceStr: "61.8万",
      unitPriceStr: "7254元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111911198.html",
      cardType: "二手房",
    },
    {
      title: "纬二路昌建誉峰毛坯三房加10个平方，带8平储藏室",
      desc: "3室1厅/115.91㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_wo9cTdGcz_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "69.6万",
      unitPriceStr: "6005元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110940809.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰精装两房，家具家电齐全，拎包入住，双气地暖",
      desc: "2室2厅/97.95㎡/西/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_6cMaVcIou_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "79万",
      unitPriceStr: "8066元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110860073.html",
      cardType: "二手房",
    },
    {
      title: "小区物业管理完善·环境优美，交通出行便利",
      desc: "3室2厅/97.62㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Src085GZP_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "65万",
      unitPriceStr: "6659元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111255542.html",
      cardType: "二手房",
    },
    {
      title: "交通方便，小区绿化好，阳光充足，精装修，看房方便",
      desc: "2室1厅/87.04㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_6HbVRKuEv_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "64.8万",
      unitPriceStr: "7445元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107646685.html",
      cardType: "二手房",
    },
    {
      title: "两室精装修，拎包入住，楼层好，采光好，老证可按揭。",
      desc: "2室2厅/87.04㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_xrrlYgG41_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "53万",
      unitPriceStr: "6090元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111283231.html",
      cardType: "二手房",
    },
    {
      title: "户型方正，南北通透.布局合理，客厅落地窗. 楼层好",
      desc: "3室2厅/142.29㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_2tsbU9hPp_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "88万",
      unitPriceStr: "6185元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110552096.html",
      cardType: "二手房",
    },
    {
      title: "位置好交通便利、配套成熟、户型好。",
      desc: "3室2厅/85.2㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_XtUnM1y5o_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "63.8万",
      unitPriceStr: "7489元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110825747.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰新型社区，环境优美，配套设施成熟",
      desc: "3室2厅/125.35㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_hX6nNCJmU_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "85万",
      unitPriceStr: "6782元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111355232.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰 精装修两房 老证可按揭",
      desc: "2室2厅/83.96㎡/南/昌建誉峰",
      tags: [],
      coverPic: null,
      priceStr: "52万",
      unitPriceStr: "6194元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111925596.html",
      cardType: "二手房",
    },
    {
      title: "位置好交通便利、配套成熟、户型好。",
      desc: "3室2厅/85.2㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_XtUnM1y5o_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "63.8万",
      unitPriceStr: "7489元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110825747.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰，一口带院，带负一层，家具家电可按揭",
      desc: "4室2厅/115.61㎡/南 北/昌建誉峰",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_vhvD2Dg3a_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "107万",
      unitPriceStr: "9256元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109928556.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰 精装小三房未入住 双气有地暖 采光充足",
      desc: "3室1厅/88.23㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_QOMrCBnKW_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "62.8万",
      unitPriceStr: "7118元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109748662.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰位于少年宫旁边，交通便利",
      desc: "3室2厅/98.54㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_I6UuyeIb4_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "60万",
      unitPriceStr: "6089元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110834727.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰，交通便利，购物方便，环境优美。双气",
      desc: "3室2厅/98.15㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Oo4MQp9SK_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "69.8万",
      unitPriceStr: "7112元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106180494.html",
      cardType: "二手房",
    },
    {
      title: "得房率高边户学，校公园就在家门口诚心出售",
      desc: "3室1厅/97.95㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_lExXGSmdc_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "52万",
      unitPriceStr: "5309元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111309549.html",
      cardType: "二手房",
    },
    {
      title: "位置好交通便利、配套成熟、户型好。",
      desc: "3室2厅/98.96㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_G04trKqBA.jpg.210x164.jpg?from=ke.com",
      priceStr: "63.9万",
      unitPriceStr: "6458元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111702014.html",
      cardType: "二手房",
    },
    {
      title: "昌建誉峰，环境优美，交通便利，市政供暖",
      desc: "2室2厅/87.02㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_7Yvep1All_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "58万",
      unitPriceStr: "6666元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111093937.html",
      cardType: "二手房",
    },
    {
      title: "楼层佳，视野开阔。带地暖全屋品牌定制。",
      desc: "3室2厅/115.91㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_lw1XRgsbw.jpg.210x164.jpg?from=ke.com",
      priceStr: "79.5万",
      unitPriceStr: "6859元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110252360.html",
      cardType: "二手房",
    },
    {
      title: "地理位置好，交通便利，精装修，家电家具齐全",
      desc: "2室2厅/87.35㎡/南/昌建誉峰",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/dc453b69d6c38aa0b10f262ffe4fdc60-030.jpg.210x164.jpg?from=ke.com",
      priceStr: "66万",
      unitPriceStr: "7556元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106452895.html",
      cardType: "二手房",
    },
    {
      title: "楼层佳，视野开阔。带地暖全屋品牌定制。",
      desc: "3室2厅/115.91㎡/南/昌建誉峰",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_lw1XRgsbw.jpg.210x164.jpg?from=ke.com",
      priceStr: "79.5万",
      unitPriceStr: "6859元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110252360.html",
      cardType: "二手房",
    },
  ],
};
