// 天中国际
export const tzgj: Object = {
  total: 77,
  list: [
    {
      title: "小区环境好，房东急售，价格可议",
      desc: "1室1厅/43.5㎡/南/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Yjq071QgE_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "19万",
      unitPriceStr: "4368元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109972374.html",
      cardType: "二手房",
    },
    {
      title: "房东急售，看房提前联系，，，，，，",
      desc: "1室1厅/43.5㎡/东/天中国际",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/e54ec85ed24c6a4ddceea6099f446607-069.jpg.210x164.jpg?from=ke.com",
      priceStr: "22万",
      unitPriceStr: "5058元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107668501.html",
      cardType: "二手房",
    },
    {
      title: "户型方正，格局分布合理，居住舒适，难得的好房子",
      desc: "1室1厅/49.18㎡/东 南 西 北/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_GDrryaspB_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "22.9万",
      unitPriceStr: "4657元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111971796.html",
      cardType: "二手房",
    },
    {
      title: "小区环境优美，绿化面积覆盖高，干净整洁",
      desc: "1室1厅/50.34㎡/北/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_BkJXfwKx8_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "25万",
      unitPriceStr: "4967元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110580713.html",
      cardType: "二手房",
    },
    {
      title: "小区环境优美，绿化面积覆盖高，干净整洁",
      desc: "1室1厅/50.34㎡/北/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_UfQKaVBWN_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "25万",
      unitPriceStr: "4967元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110580763.html",
      cardType: "二手房",
    },
    {
      title: "（天中国际1-1-1-1 45.81m² 25.8 万）",
      desc: "1室1厅/45.81㎡/南/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_DjH7jAhJb_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "25.8万",
      unitPriceStr: "5632元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112136639.html",
      cardType: "二手房",
    },
    {
      title: "房源户型，方正，空间感好，通透性好.居住舒适。",
      desc: "1室1厅/54.7㎡/北/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_uVLvcZwTN_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "26万",
      unitPriceStr: "4754元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110580773.html",
      cardType: "二手房",
    },
    {
      title: "位置好 交通方便 布局合理 采光充足",
      desc: "1室1厅/54.7㎡/南/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Yz4eQrh0p_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "28万",
      unitPriceStr: "5119元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107430038.html",
      cardType: "二手房",
    },
    {
      title: "小区环境优美，绿化面积覆盖高，居民素质高",
      desc: "1室1厅/66.71㎡/北/天中国际",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Se8oNYyR7_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "32万",
      unitPriceStr: "4797元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110580665.html",
      cardType: "二手房",
    },
    {
      title: "户型方正，格局分布合理，居住舒适，难得的好房子",
      desc: "2室1厅/98.93㎡/南/天中国际",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_TeC1YsMwC_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "50万",
      unitPriceStr: "5055元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112013603.html",
      cardType: "二手房",
    },
  ],
  page: 1,
  pagesize: 10,
  resblockCard: {
    communityId: 8872131174126173,
    communityName: "天中国际",
    communityDesc: "塔楼 塔板结合 | 共21栋 4142户 | 2008-2020年",
    avgUnitPrice: 6311,
    avgUnitPriceDesc: "0.63万元/㎡",
    count: 77,
    countDesc: '在售<i class="_color">77</i>套房源',
    actionUrl: "https://zmd.ke.com/xiaoqu/8872131174126173/",
  },
};
