// 香水湾
export const xsw: any = {
  total: 93,
  page: 1,
  pagesize: 10,
  resblockCard: {
    communityId: 8872131184606331,
    communityName: "香水湾",
    communityDesc: "塔楼 板楼 | 共11栋 2841户 | 2006-2020年",
    avgUnitPrice: 6321,
    avgUnitPriceDesc: "0.63万元/㎡",
    count: 93,
    countDesc: '在售<i class="_color">93</i>套房源',
    actionUrl: "https://zmd.ke.com/xiaoqu/8872131184606331/",
  },
  list: [
    {
      title: "毛坯三房，中间楼层，双气市政大暖，东户，采光好。",
      desc: "3室2厅/137.62㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_o1BTFr0uq_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "90万",
      unitPriceStr: "6540元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110578668.html",
      cardType: "二手房",
    },
    {
      title: "香水湾，毛坯三房中间楼层，双气市政大暖，采光好。",
      desc: "3室2厅/117.2㎡/南 北/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Y0mwLZqag_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "72.5万",
      unitPriceStr: "6187元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104104951630.html",
      cardType: "二手房",
    },
    {
      title: "在天中广场旁香水湾40年公寓。。。。。。。。。",
      desc: "1室1厅/42.26㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_P8dMYUqkE_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "17.8万",
      unitPriceStr: "4213元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110875439.html",
      cardType: "二手房",
    },
    {
      title: "香水湾住宅小区湖景房南北朝向老证可按揭",
      desc: "3室2厅/135.13㎡/南/香水湾",
      tags: [],
      coverPic: null,
      priceStr: "90万",
      unitPriceStr: "6661元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111228909.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 2室1厅 南",
      desc: "2室1厅/63.25㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_9xoT0By8C_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "42.5万",
      unitPriceStr: "6720元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111777958.html",
      cardType: "二手房",
    },
    {
      title: "香水湾住宅公寓精装修拎包入住方便",
      desc: "1室1厅/65.87㎡/南 北/香水湾",
      tags: [],
      coverPic: null,
      priceStr: "41.5万",
      unitPriceStr: "6301元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111434679.html",
      cardType: "二手房",
    },
    {
      title: "市府旁边，开源河畔，行 政中 心，环境好，出行方便。",
      desc: "2室2厅/99.86㎡/南/香水湾",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/ca8d2078ef0e24921bd5624daf763b42-089.jpg.210x164.jpg?from=ke.com",
      priceStr: "73.8万",
      unitPriceStr: "7391元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106450442.html",
      cardType: "二手房",
    },
    {
      title: "小区环境优美，市政供暖，交通便利，出行方便",
      desc: "3室2厅/133.7㎡/南 北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Axie0fLIz.jpg.210x164.jpg?from=ke.com",
      priceStr: "83万",
      unitPriceStr: "6208元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109591822.html",
      cardType: "二手房",
    },
    {
      title: "香水湾，精装1房1厅，，双气市政大暖，采光好。",
      desc: "1室1厅/68.79㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_PsyvbsTsb_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "46万",
      unitPriceStr: "6688元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109973397.html",
      cardType: "二手房",
    },
    {
      title: "开源河畔，环境好，出行方便。楼层佳",
      desc: "2室2厅/91.98㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_QE4sBcIC8_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "62.5万",
      unitPriceStr: "6795元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104104348031.html",
      cardType: "二手房",
    },
    {
      title: "朝向好，楼层佳，诚意卖，户型方正",
      desc: "3室2厅/94.5㎡/南 北/香水湾",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/7bae5552fe4463f3031bafa43639f7fa-069.jpg.210x164.jpg?from=ke.com",
      priceStr: "68万",
      unitPriceStr: "7196元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108060269.html",
      cardType: "二手房",
    },
    {
      title: "香水湾公寓，大单间，根据喜好装修，楼层好",
      desc: "1室1厅/61.11㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_VFck3aDJk_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "33.8万",
      unitPriceStr: "5532元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111682752.html",
      cardType: "二手房",
    },
    {
      title: "新市委旁 香水湾 双气精装两室 老证可按揭",
      desc: "2室2厅/92.15㎡/南/香水湾",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/b892b5fc68b8d80fa57db4785c020309-047.jpg.210x164.jpg?from=ke.com",
      priceStr: "54.5万",
      unitPriceStr: "5915元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106138923.html",
      cardType: "二手房",
    },
    {
      title: "香水湾精装修1室 采光好 家具家电齐全",
      desc: "1室1厅/42.26㎡/北/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_vG3Nr3wdd_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "17.5万",
      unitPriceStr: "4142元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112054584.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 1室1厅 南",
      desc: "1室1厅/37.7㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_bsTJc2cpF_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "16万",
      unitPriceStr: "4245元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111503069.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 住 宅 精装一室 带家具家电 有证",
      desc: "1室0厅/43.54㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_EkLkIFL81_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "29万",
      unitPriceStr: "6661元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108638265.html",
      cardType: "二手房",
    },
    {
      title: "香水湾三室两厅两位，精装有证可按揭，环境好交通便利",
      desc: "3室2厅/137.4㎡/南/香水湾",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/a4ae5db2b5417d90891994d2d95e8bc2-071.jpg.210x164.jpg?from=ke.com",
      priceStr: "88.8万",
      unitPriceStr: "6463元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104103413656.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 环境好 采光好  老证  3室2厅2卫",
      desc: "3室2厅/132.12㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_AwH8gjIbP_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "78万",
      unitPriceStr: "5904元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107515371.html",
      cardType: "二手房",
    },
    {
      title: "香水湾精装修老证可按揭楼层好看房方便",
      desc: "3室2厅/131.96㎡/东 南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_oKJo1CH9V.jpg.210x164.jpg?from=ke.com",
      priceStr: "92.6万",
      unitPriceStr: "7018元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109549925.html",
      cardType: "二手房",
    },
    {
      title: "地段好...价格便宜.配套齐全..",
      desc: "2室2厅/92.13㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_0IvSEPRZJ_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "56万",
      unitPriceStr: "6079元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108536421.html",
      cardType: "二手房",
    },
    {
      title: "（香水湾1-1-1-1 41.50m² 25 万）",
      desc: "1室1厅/41.5㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_zXE9ZVme0.jpg.210x164.jpg?from=ke.com",
      priceStr: "21.6万",
      unitPriceStr: "5205元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108871478.html",
      cardType: "二手房",
    },
    {
      title: "多层温馨小三房，全屋带家具家电",
      desc: "3室2厅/94.5㎡/南/香水湾",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/43638742cbadafc90a108046138c2f93-079.jpg.210x164.jpg?from=ke.com",
      priceStr: "62万",
      unitPriceStr: "6561元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111412498.html",
      cardType: "二手房",
    },
    {
      title: "香水湾精装小三房，交通便利，配套成熟",
      desc: "3室2厅/101.71㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_3tz36E4Oj_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "78万",
      unitPriceStr: "7669元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111129892.html",
      cardType: "二手房",
    },
    {
      title: "户型方正，布局合理，临开源公园，地段佳。",
      desc: "1室0厅/36㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_6aang34aR_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "26.8万",
      unitPriceStr: "7445元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111822179.html",
      cardType: "二手房",
    },
    {
      title: "急售！香水湾 老证，精装修，双气  位置优越",
      desc: "1室1厅/65.89㎡/东/香水湾",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_m9TOtLNxb_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "39万",
      unitPriceStr: "5919元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111839343.html",
      cardType: "二手房",
    },
    {
      title: "急售！开源河旁香水湾精装修，双气",
      desc: "2室2厅/91.98㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_j1nX8ykPc_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "57万",
      unitPriceStr: "6197元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111019480.html",
      cardType: "二手房",
    },
    {
      title: "急售！老证，看房方便。双气，通透户型",
      desc: "3室2厅/130.06㎡/南 北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_0w52OiYWN_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "79.8万",
      unitPriceStr: "6136元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110800942.html",
      cardType: "二手房",
    },
    {
      title: "急售！看房方便，香水湾70年住宅性公寓.",
      desc: "1室1厅/68.79㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_FFZG3i932_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "39.8万",
      unitPriceStr: "5786元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111413734.html",
      cardType: "二手房",
    },
    {
      title: "精装一室    拎包入住老证可按揭",
      desc: "1室0厅/45.27㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_MfEDb0LnM.jpg.210x164.jpg?from=ke.com",
      priceStr: "26万",
      unitPriceStr: "5744元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110489129.html",
      cardType: "二手房",
    },
    {
      title: "环境优美，市政供暖，交通便利，戶型好。",
      desc: "3室2厅/135.13㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_8C0hfQEQa_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "96万",
      unitPriceStr: "7105元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111444679.html",
      cardType: "二手房",
    },
    {
      title: "急售！老证，看房方便。双气，通透户型",
      desc: "3室2厅/130.06㎡/南 北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_0w52OiYWN_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "79.8万",
      unitPriceStr: "6136元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110800942.html",
      cardType: "二手房",
    },
    {
      title: "急售！看房方便，香水湾70年住宅性公寓.",
      desc: "1室1厅/68.79㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_FFZG3i932_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "39.8万",
      unitPriceStr: "5786元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111413734.html",
      cardType: "二手房",
    },
    {
      title: "香水湾，两室两厅一卫，精装修带家具家电，老证",
      desc: "2室2厅/101.14㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_gH47GXs1h_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "62万",
      unitPriceStr: "6131元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111020692.html",
      cardType: "二手房",
    },
    {
      title: "精装一室    拎包入住老证可按揭",
      desc: "1室0厅/45.27㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_MfEDb0LnM.jpg.210x164.jpg?from=ke.com",
      priceStr: "26万",
      unitPriceStr: "5744元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110489129.html",
      cardType: "二手房",
    },
    {
      title: "房子装修齐全拎包入住，价格可谈，看房方便",
      desc: "2室2厅/92.13㎡/西南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_eOwX5GHIG_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "58万",
      unitPriceStr: "6296元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107235899.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 精装修 两梯四户 老证 小区环境",
      desc: "2室2厅/92.13㎡/南/香水湾",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/084714db813aefd15732b1995c64e6d2-098.jpg.210x164.jpg?from=ke.com",
      priceStr: "65万",
      unitPriceStr: "7056元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109923969.html",
      cardType: "二手房",
    },
    {
      title: "北区，满五唯一，香水湾，三室两厅两卫，体育场",
      desc: "3室2厅/131.45㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_GL3dqzGn9_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "92.8万",
      unitPriceStr: "7060元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111402473.html",
      cardType: "二手房",
    },
    {
      title: "香水湾--好楼层--两房--拎包即住",
      desc: "2室2厅/92.47㎡/南/香水湾",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/hdic-frame/f9dbac93-a8b4-44f8-bd5e-c4d35dba4f34.jpg.210x164.jpg?from=ke.com",
      priceStr: "60万",
      unitPriceStr: "6489元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111412579.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 三房 精装 老证 看房方便",
      desc: "3室2厅/130㎡/南 北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Dph9LOuWz_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "89.8万",
      unitPriceStr: "6908元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111424648.html",
      cardType: "二手房",
    },
    {
      title: "香水湾精装大三房出售，老证，楼层好，房东诚心出售",
      desc: "3室2厅/132.12㎡/西/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_96b9rBmHH_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "95万",
      unitPriceStr: "7191元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111810961.html",
      cardType: "二手房",
    },
    {
      title: "：人车分流适合刚结婚的年轻人首付比例不高合老年人",
      desc: "1室1厅/45.27㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "房主自荐",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_mOnHo0yib_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "25.5万",
      unitPriceStr: "5633元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107993396.html",
      cardType: "二手房",
    },
    {
      title: "香水湾单间出售，楼层好，交通便利",
      desc: "1室1厅/46.89㎡/西/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_cW6EtC4Xc_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "28.8万",
      unitPriceStr: "6143元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111257739.html",
      cardType: "二手房",
    },
    {
      title: "香水湾单身公寓房东急售，随时可以装修",
      desc: "1室0厅/41.53㎡/北/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_KaOXuqXOi_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "15.8万",
      unitPriceStr: "3805元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108659867.html",
      cardType: "二手房",
    },
    {
      title: "急售 香水湾一室一厅精装 随时看房",
      desc: "1室1厅/41.63㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_WiYyunVv7_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "23.8万",
      unitPriceStr: "5718元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111209370.html",
      cardType: "二手房",
    },
    {
      title: "市府旁边，开源河畔，前排观景房，出行方便，",
      desc: "3室2厅/136.05㎡/南/香水湾",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/2c773033ac9dac2411fd0f9a842d5c6a-004.jpg.210x164.jpg?from=ke.com",
      priceStr: "90万",
      unitPriceStr: "6616元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106036133.html",
      cardType: "二手房",
    },
    {
      title: "香水湾单间公寓，精装修，业主诚心出售",
      desc: "1室1厅/41.93㎡/北/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_BsUlxrB2O_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "23万",
      unitPriceStr: "5486元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111194052.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 带车位储藏室 交通便利 生活配套齐全",
      desc: "3室2厅/94.5㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_WreUDeUXm_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "71.5万",
      unitPriceStr: "7567元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107367925.html",
      cardType: "二手房",
    },
    {
      title: "香水湾   一室一厅 住宅 朝东   自住或做办公室均可",
      desc: "1室0厅/37.62㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_sQPSyxiqa_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "26.5万",
      unitPriceStr: "7045元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107652895.html",
      cardType: "二手房",
    },
    {
      title: "2.香水湾  精装修，一室一厅 即买  即入住",
      desc: "1室1厅/45.27㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_F70tgLflL.jpg.210x164.jpg?from=ke.com",
      priceStr: "26.5万",
      unitPriceStr: "5854元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112005648.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 精装一室 住宅 独立厨卫 老证",
      desc: "1室1厅/36.79㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_NdaG2J3wd_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "28.5万",
      unitPriceStr: "7747元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111379603.html",
      cardType: "二手房",
    },
    {
      title: "香水湾老证，精装三房，带全屋家居家电通透户型双气",
      desc: "3室1厅/117.2㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_4EPPWmg4g_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "76万",
      unitPriceStr: "6485元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111853184.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 标准 一室一厅 一厨一卫 拎包入住",
      desc: "1室1厅/46.07㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_k7FWKcoOm_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "26.7万",
      unitPriceStr: "5796元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112050041.html",
      cardType: "二手房",
    },
    {
      title: "临开源公园，交通便利，小区环境优美，户型好，采光佳",
      desc: "1室1厅/37.7㎡/东/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_t3wIUrsNP_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "21.6万",
      unitPriceStr: "5730元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111731529.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 精装一室 带家具家电 朝东 有证",
      desc: "1室1厅/37.62㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_N7j94qrYS_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "27万",
      unitPriceStr: "7178元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108638475.html",
      cardType: "二手房",
    },
    {
      title: "香水湾2室出售 体育场 开源湖地理位置优越出行方便",
      desc: "2室2厅/91.98㎡/南 西/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_4UXeIxZ1P_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "65万",
      unitPriceStr: "7067元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110924220.html",
      cardType: "二手房",
    },
    {
      title: "香水湾小公寓随时看房.........",
      desc: "2室0厅/67.11㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_yaOcv2feE_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "33.8万",
      unitPriceStr: "5037元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107887253.html",
      cardType: "二手房",
    },
    {
      title: "天中广场旁，香水湾，三房精装户型好，老证",
      desc: "3室2厅/94.5㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_O7wCe7mDX_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "69.8万",
      unitPriceStr: "7387元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110286501.html",
      cardType: "二手房",
    },
    {
      title: "急售香水湾一室一厅精装修，纯南户采光好楼层佳",
      desc: "1室1厅/47.65㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_L5t7E5oyz_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "25.9万",
      unitPriceStr: "5436元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111713020.html",
      cardType: "二手房",
    },
    {
      title: "市政府旁 精装修一室  家具家店齐全，  干净整洁 老证",
      desc: "1室1厅/42.26㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_qh6M5eqjc_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "18.8万",
      unitPriceStr: "4449元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111093178.html",
      cardType: "二手房",
    },
    {
      title: "香水湾  三室两厅一厨两卫   通透户型",
      desc: "3室2厅/132.12㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Tmo4Y5NoL_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "98万",
      unitPriceStr: "7418元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110719377.html",
      cardType: "二手房",
    },
    {
      title: "一楼带小院双气精装2房户型好采光好",
      desc: "3室2厅/94.5㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/0a649231-a694-406e-a41c-57ab160afea3_1000.jpg.210x164.jpg?from=ke.com",
      priceStr: "80万",
      unitPriceStr: "8466元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112153765.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 2室1厅 北",
      desc: "2室1厅/64.41㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_PrZGKDE2t_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "30万",
      unitPriceStr: "4658元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111507088.html",
      cardType: "二手房",
    },
    {
      title: "毛坯三房可随意装修，通厅通透，客厅朝南，三卧飘窗。",
      desc: "3室2厅/137.62㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_fMCDlHzix_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "92万",
      unitPriceStr: "6686元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109644877.html",
      cardType: "二手房",
    },
    {
      title: "香水湾，精装带天然气，全屋品牌家具家电，可拎包入住",
      desc: "1室1厅/47.37㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_0w5vTgMI4_2.jpg.210x164.jpg?from=ke.com",
      priceStr: "26万",
      unitPriceStr: "5489元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111696319.html",
      cardType: "二手房",
    },
    {
      title: "70年住宅公寓，位置好，毛坯可随意装修",
      desc: "1室1厅/45.27㎡/西/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Kkn2BZRDW_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "27万",
      unitPriceStr: "5965元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107540271.html",
      cardType: "二手房",
    },
    {
      title: "地理位置优越，交通方便，楼层佳。",
      desc: "1室1厅/65.87㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_O47E0we0x_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "33.6万",
      unitPriceStr: "5101元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110659178.html",
      cardType: "二手房",
    },
    {
      title: "市府旁，小河畔，精装两室，双气入户，拎包",
      desc: "2室2厅/92.47㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_FxmKAPCec_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "60万",
      unitPriceStr: "6489元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108841029.html",
      cardType: "二手房",
    },
    {
      title: "精装修，老证，交通便利，户型方正",
      desc: "2室2厅/103㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_88b23a1Uj_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "55万",
      unitPriceStr: "5340元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110860055.html",
      cardType: "二手房",
    },
    {
      title: "急售！满五，精装修，户型方正，双气",
      desc: "2室2厅/92.47㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_GAksrzwoQ_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "54万",
      unitPriceStr: "5840元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110801743.html",
      cardType: "二手房",
    },
    {
      title: "户型方正，格局分布合理，难得的好房.带储藏室和车位",
      desc: "2室2厅/99.86㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_qQN1Kor2G_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "60万",
      unitPriceStr: "6009元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106765308.html",
      cardType: "二手房",
    },
    {
      title: "毛坯三房可随意装修，通厅通透，客厅朝南，三卧飘窗。",
      desc: "3室2厅/137.62㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_fMCDlHzix_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "92万",
      unitPriceStr: "6686元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109644877.html",
      cardType: "二手房",
    },
    {
      title: "70年住宅公寓，位置好，毛坯可随意装修",
      desc: "1室1厅/45.27㎡/西/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_Kkn2BZRDW_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "27万",
      unitPriceStr: "5965元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107540271.html",
      cardType: "二手房",
    },
    {
      title: "急售！满五，精装修，户型方正，双气",
      desc: "2室2厅/92.47㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_GAksrzwoQ_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "54万",
      unitPriceStr: "5840元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110801743.html",
      cardType: "二手房",
    },
    {
      title: "香水湾小区 小河边 三房 看房方便 老证",
      desc: "3室2厅/135.13㎡/南/香水湾",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/f0fafd78d9eda507508d5195b1c41b93-022.jpg.210x164.jpg?from=ke.com",
      priceStr: "79万",
      unitPriceStr: "5847元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109746087.html",
      cardType: "二手房",
    },
    {
      title: "小区地理位置优越，交通方便  布局合理 小区位置好",
      desc: "1室1厅/45.27㎡/东/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_U2fnJt5TH_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "28.2万",
      unitPriceStr: "6230元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109104580.html",
      cardType: "二手房",
    },
    {
      title: "南北通厅通透两卧朝阳双气老证。",
      desc: "4室2厅/136.05㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_dCcpNWk63_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "96万",
      unitPriceStr: "7057元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111861542.html",
      cardType: "二手房",
    },
    {
      title: "香水湾大三房，双气市政供暖。。",
      desc: "3室2厅/136.05㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_UwK6KXI7I_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "88万",
      unitPriceStr: "6469元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110784760.html",
      cardType: "二手房",
    },
    {
      title: "精装修，位置便利，环境优美，房东诚心卖",
      desc: "1室1厅/64.41㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_ulQO0H7jo_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "38万",
      unitPriceStr: "5900元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109884753.html",
      cardType: "二手房",
    },
    {
      title: "香水湾装修好一天未入住，看房有钥匙，",
      desc: "2室2厅/92.15㎡/东南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_rMBz6raDG_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "52.6万",
      unitPriceStr: "5709元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110554581.html",
      cardType: "二手房",
    },
    {
      title: "开源湖旁.黄淮学院.精装.采光好",
      desc: "3室2厅/137.62㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_rIMiodYi2.jpg.210x164.jpg?from=ke.com",
      priceStr: "108万",
      unitPriceStr: "7848元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110516575.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 精装一室 独立厨卫 阳台 双气 老证",
      desc: "1室0厅/36.79㎡/北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_VsOe1sJT4_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "25.8万",
      unitPriceStr: "7013元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111886713.html",
      cardType: "二手房",
    },
    {
      title: "急售！老证，看房方便。双气，户型通透。",
      desc: "2室2厅/101.14㎡/东/香水湾",
      tags: [
        {
          desc: "新上房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/hdic-frame/1ad74d73-451d-4514-9338-97993402aee5.png.210x164.jpg?from=ke.com",
      priceStr: "60万",
      unitPriceStr: "5933元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112197371.html",
      cardType: "二手房",
    },
    {
      title: "香水湾，老证，半装修，7楼 ，位置好",
      desc: "3室2厅/101.71㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_JE3yapBwm_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "62万",
      unitPriceStr: "6096元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111471373.html",
      cardType: "二手房",
    },
    {
      title: "香水湾 精装修 一室一厅 诚心出售",
      desc: "1室1厅/46.07㎡/北/香水湾",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/hdic-frame/5884f35a-0e51-42f9-baa4-2b9556b91e56.jpg.210x164.jpg?from=ke.com",
      priceStr: "27万",
      unitPriceStr: "5861元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112052268.html",
      cardType: "二手房",
    },
    {
      title: "香水湾拎包过去即可精装修位置不错",
      desc: "1室1厅/67.11㎡/东南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_siT8nqN83_2.jpg.210x164.jpg?from=ke.com",
      priceStr: "35.6万",
      unitPriceStr: "5305元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111505648.html",
      cardType: "二手房",
    },
    {
      title: "小区环境幽静，绿化高，配套齐全，交通便利，",
      desc: "1室1厅/42.26㎡/南/香水湾",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_IJvxwbJzf_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "25万",
      unitPriceStr: "5916元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111888778.html",
      cardType: "二手房",
    },
    {
      title: "业主急售 诚心出售 价位可谈 房子采光好 可随时看房",
      desc: "3室2厅/94.5㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_1pH2lAo9K_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "63.8万",
      unitPriceStr: "6752元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111299767.html",
      cardType: "二手房",
    },
    {
      title: "小区环境优美，市政供暖 地下停车位交通便利出行方便",
      desc: "2室2厅/93.55㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_kwilZkU4Z.jpg.210x164.jpg?from=ke.com",
      priceStr: "60万",
      unitPriceStr: "6414元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110507685.html",
      cardType: "二手房",
    },
    {
      title: "香水湾2室一厅一卫---好楼层---采光不错",
      desc: "2室2厅/93.55㎡/南 北/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_43fvDXVvq.jpg.210x164.jpg?from=ke.com",
      priceStr: "60万",
      unitPriceStr: "6414元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111802699.html",
      cardType: "二手房",
    },
    {
      title: "香水湾精装2房，业主诚心出售，交通便利",
      desc: "2室2厅/92.47㎡/南/香水湾",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_XhlgdHi51_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "55万",
      unitPriceStr: "5948元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111529624.html",
      cardType: "二手房",
    },
  ],
};
