// 置地花园-21-6400
export const zdhy: Object = {
  fbQueryId: "",
  feedQueryId: "lSEvSmqdiR2JMDRn",
  list: [
    {
      title: "慎阳路竹沟路，置地花园，一楼带活院，有证可按揭",
      desc: "1室1厅/46.32㎡/南/置地花园",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/c6eeef1f6d652404876a0d4b2c50b2f7-015.jpg.210x164.jpg?from=ke.com",
      priceStr: "41.8万",
      unitPriceStr: "9025元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104105912377.html",
      cardType: "二手房",
    },
    {
      title: "置地花园大品牌社区，环境优美，交通便利",
      desc: "2室2厅/93㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_DUBLwxxuq_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "53万",
      unitPriceStr: "5699元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111889820.html",
      cardType: "二手房",
    },
    {
      title: "置地花园 精装两室 老证可按揭 看房方便",
      desc: "2室2厅/91.57㎡/西南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_HJmBWrn6S_2.jpg.210x164.jpg?from=ke.com",
      priceStr: "55万",
      unitPriceStr: "6007元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110871524.html",
      cardType: "二手房",
    },
    {
      title: "置地花园，双气，毛坯两房，有证可按揭贷款",
      desc: "2室2厅/91.31㎡/南/置地花园",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/b0f215d787c2eee4a77cd61befb7f07d-091.jpg.210x164.jpg?from=ke.com",
      priceStr: "56万",
      unitPriceStr: "6133元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104104254987.html",
      cardType: "二手房",
    },
    {
      title: "房东  价格可谈 房东实在  户型方正",
      desc: "2室2厅/93.75㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_A7ep7Q2Rl.jpg.210x164.jpg?from=ke.com",
      priceStr: "58万",
      unitPriceStr: "6187元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109299708.html",
      cardType: "二手房",
    },
    {
      title: "中间楼层，全明采光，小区环境优美",
      desc: "2室2厅/91.57㎡/西南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_SYhXZ5klj_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "59.5万",
      unitPriceStr: "6498元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111229830.html",
      cardType: "二手房",
    },
    {
      title: "小区环境好 户型方正 交通便利",
      desc: "2室2厅/91.31㎡/东南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_E6uSvDxlp_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "59.8万",
      unitPriceStr: "6550元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106540011.html",
      cardType: "二手房",
    },
    {
      title: "户型方正 采光好 小区为置地品牌，物业服务好",
      desc: "2室1厅/95.14㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_lK7GcN3rf_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "61万",
      unitPriceStr: "6412元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104108255223.html",
      cardType: "二手房",
    },
    {
      title: "置地花园，2室2厅1卫，边户，老证过户费低",
      desc: "2室2厅/95.14㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_bIZpFge8k_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "62万",
      unitPriceStr: "6517元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112005816.html",
      cardType: "二手房",
    },
    {
      title: "置地花园 市政府旁 双气 视野开阔  配套齐全",
      desc: "2室2厅/91.31㎡/南/置地花园",
      tags: [],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/dc86e3ddc85a714d21116c0b2912b81d-036.jpg.210x164.jpg?from=ke.com",
      priceStr: "62.5万",
      unitPriceStr: "6845元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111227441.html",
      cardType: "二手房",
    },
    {
      title: "置地花园品质社区，交通便利，环境优美",
      desc: "2室2厅/94㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_jYWSj6tsI.jpg.210x164.jpg?from=ke.com",
      priceStr: "62.5万",
      unitPriceStr: "6649元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112011413.html",
      cardType: "二手房",
    },
    {
      title: "置地物业管理规范，小区楼间距宽，大落地窗阳台，双气",
      desc: "2室2厅/95.14㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_f8GXue3kD_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "62.8万",
      unitPriceStr: "6601元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110566540.html",
      cardType: "二手房",
    },
    {
      title: "12层洋房两室 精装修 老证 采光好 位置佳 朝南",
      desc: "2室1厅/95.14㎡/南/置地花园",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_cjiWsPWJY.jpg.210x164.jpg?from=ke.com",
      priceStr: "65万",
      unitPriceStr: "6833元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112050383.html",
      cardType: "二手房",
    },
    {
      title: "置 地 花 园  拎 包 入 住    配 套 齐 全",
      desc: "2室2厅/91.57㎡/南/置地花园",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/41481a8e8c021cf7580bbc1b63de9e7f-094.jpg.210x164.jpg?from=ke.com",
      priceStr: "69万",
      unitPriceStr: "7536元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104105761508.html",
      cardType: "二手房",
    },
    {
      title: "置地花园位于慎阳路与竹沟路交叉口",
      desc: "3室2厅/122.47㎡/南 北/置地花园",
      tags: [
        {
          desc: "VR房源",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_WbN48aGtJ_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "69.8万",
      unitPriceStr: "5700元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104110074833.html",
      cardType: "二手房",
    },
    {
      title: "置地花园，老证，采光好，看房有钥匙，简单装修",
      desc: "3室2厅/127.56㎡/北/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_w1DZuG4z1_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "71.8万",
      unitPriceStr: "5629元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112179667.html",
      cardType: "二手房",
    },
    {
      title: "置地花园 近市政府 生活配套成熟",
      desc: "3室2厅/122.47㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_2nyvUbHoS_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "76.5万",
      unitPriceStr: "6247元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104111213514.html",
      cardType: "二手房",
    },
    {
      title: "市政府北置地花园毛坯双气老证户型方正采光好诚意出售",
      desc: "3室2厅/140.76㎡/南 北/置地花园",
      tags: [
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "房主自荐",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/3b5da2a8fbcb6098527fd9477078a717-090.jpg.210x164.jpg?from=ke.com",
      priceStr: "78.8万",
      unitPriceStr: "5599元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104107295813.html",
      cardType: "二手房",
    },
    {
      title: "置地花园 精装三室 双气 老证",
      desc: "3室2厅/122.47㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_UQXHUKGF6_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "79.8万",
      unitPriceStr: "6516元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104109924169.html",
      cardType: "二手房",
    },
    {
      title: "此房是东户顶楼，户型方正，采光好。老证可按揭",
      desc: "3室2厅/140.76㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
        {
          desc: "随时可看",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_mLbbnhK3Y_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "84万",
      unitPriceStr: "5968元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104106021394.html",
      cardType: "二手房",
    },
    {
      title: "置地花园 3室2厅 南",
      desc: "3室2厅/140.76㎡/南/置地花园",
      tags: [
        {
          desc: "VR看装修",
          color: "849AAE",
          bgColor: "",
          boldFont: 0,
        },
      ],
      coverPic: "https://ke-image.ljcdn.com/110000-inspection/pc1_mDeZnb44P_1.jpg.210x164.jpg?from=ke.com",
      priceStr: "85万",
      unitPriceStr: "6039元/平",
      actionUrl: "https://zmd.ke.com/ershoufang/104112008952.html",
      cardType: "二手房",
    },
  ],
  total: 21,
  page: 2,
  pagesize: 10,
  resblockCard: {
    communityId: 8872131254850892,
    communityName: "置地花园",
    communityDesc: "塔楼 | 共3栋 699户 | 2012-2017年",
    avgUnitPrice: 6437,
    avgUnitPriceDesc: "0.64万元/㎡",
    count: 21,
    countDesc: '在售<i class="_color">21</i>套房源',
    actionUrl: "https://zmd.ke.com/xiaoqu/8872131254850892/",
  },
  hasMore: 1,
};
